packages:
  - packages/*
catalog:
  "@changesets/changelog-github": ^0.5.1
  "@changesets/cli": ^2.28.1
  "@luxass/eslint-config": ^4.17.1
  "@types/fs-extra": ^11.0.4
  "@types/node": ^22.10.0
  "@types/semver": ^7.5.8
  "@types/yargs-parser": ^21.0.3
  "@vitest/coverage-v8": ^3.0.8
  "@vitest/ui": ^3.0.8
  eslint: ^9.22.0
  farver: ^0.4.2
  fs-extra: ^11.3.0
  msw: ^2.7.3
  semver: ^7.7.1
  tsup: ^8.4.0
  turbo: ^2.4.4
  typescript: ^5.8.2
  vitest: ^3.0.8
  vitest-testdirs: ^2.2.0
  yargs-parser: ^21.1.1
  zod: ^3.24.2
