packages:
  - packages/*

catalogs:
  monorepo:
    "@changesets/changelog-github": 0.5.2
    "@changesets/cli": 2.29.8
    turbo: 2.7.5
    msw: 2.12.7
    "@vitest/coverage-v8": 3.2.4
    "@vitest/ui": 3.2.4
    "@ark/attest": 0.56.0
    tsx: 4.21.0

  prod:
    farver: 0.4.2
    fs-extra: 11.3.3
    "@mojis/moji-compare": 0.5.0
    yargs-parser: 22.0.0
    defu: 6.1.4
    arktype: 2.1.29

  dev:
    "@luxass/eslint-config": 5.3.2
    "@types/fs-extra": 11.0.4
    "@types/node": 22.19.7
    "@mojis/loomicode": 0.2.0-beta.7
    "@types/yargs-parser": 21.0.3
    eslint: 9.30.1
    tsdown: 0.19.0
    typescript: 5.9.3
    vitest: 3.2.4
    vitest-testdirs: 4.3.0
    tsx: 4.21.0
    publint: 0.3.17

onlyBuiltDependencies:
  - esbuild
  - rolldown
