packages:
  - packages/*

catalogs:
  monorepo:
    "@changesets/changelog-github": 0.5.1
    "@changesets/cli": 2.29.6
    turbo: 2.5.6
    msw: 2.11.0
    "@vitest/coverage-v8": ^3.2.4
    "@vitest/ui": ^3.2.4
    "@ark/attest": 0.48.2
    tsx: 4.20.5

  prod:
    farver: 0.4.2
    fs-extra: 11.3.1
    "@mojis/moji-compare": 0.5.0
    yargs-parser: 22.0.0
    defu: 6.1.4
    arktype: 2.1.20

  dev:
    "@luxass/eslint-config": 5.3.0
    "@types/fs-extra": 11.0.4
    "@types/node": 22.18.0
    "@mojis/loomicode": 0.2.0-beta.7
    "@types/yargs-parser": 21.0.3
    eslint: ^9.30.1
    tsdown: 0.14.2
    typescript: 5.9.2
    vitest: ^3.2.4
    vitest-testdirs: 4.2.0
    tsx: 4.20.5
    publint: 0.3.12

onlyBuiltDependencies:
  - esbuild
  - rolldown
