packages:
  - packages/*

catalogs:
  monorepo:
    "@changesets/changelog-github": ^0.5.1
    "@changesets/cli": ^2.28.1
    turbo: ^2.4.4
    msw: ^2.7.3
    "@vitest/coverage-v8": ^3.0.9
    "@vitest/ui": ^3.0.9

  prod:
    farver: ^0.4.2
    fs-extra: ^11.3.0
    semver: ^7.7.1
    yargs-parser: ^21.1.1
    defu: ^6.1.4
    arktype: ^2.1.17

  dev:
    "@luxass/eslint-config": ^4.18.1
    "@types/fs-extra": ^11.0.4
    "@types/node": ^22.10.0
    "@types/semver": ^7.7.0
    "@mojis/loomicode": 0.2.0-beta.7
    "@types/yargs-parser": ^21.0.3
    eslint: ^9.23.0
    tsup: ^8.4.0
    typescript: ^5.8.2
    vitest: ^3.0.9
    vitest-testdirs: ^3.0.1
    tsx: ^4.19.3
  conflicts_prod_:
    fs-extra: ""
  conflicts_prod_11_3_0:
    fs-extra: 11.3.0
  conflicts_prod_c:
    fs-extra: c
  conflicts_prod_ca:
    fs-extra: ca
  conflicts_prod_cat:
    fs-extra: cat
  conflicts_prod_cata:
    fs-extra: cata
  conflicts_prod_catal:
    fs-extra: catal
  conflicts_prod_catalo:
    fs-extra: catalo
  conflicts_prod_catalog:
    fs-extra: catalog

onlyBuiltDependencies:
  - esbuild
