name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm build

      - name: lint
        run: pnpm lint

      - name: typecheck
        run: pnpm typecheck

      - name: run benchmarks
        run: pnpm bench:types -- --benchErrorOnThresholdExceeded --benchPercentThreshold 10

      - name: test
        run: pnpm test --coverage

      - name: upload coverage reports to codecov
        uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5.5.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
