name: Verify JSON Schemas

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8

      - name: setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: lts/*

      - name: install dependencies
        run: pnpm install

      - name: generate schemas
        run: pnpm run generate:json-schemas

      - name: check for git changes
        id: check-for-git-changes
        run: |
          if [ -n "$(git status --porcelain './packages/json-schemas/schemas')" ]; then
            echo "JSON Schema files have changed."
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected in JSON Schema files."
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: exit if commit to main
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && steps.check-for-git-changes.outputs.changes == 'true'
        run: |
          echo "exiting since we can't create a comment on the main branch"
          exit 0

      - name: find comment
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
        if: steps.check-for-git-changes.outputs.changes == 'true' && github.event_name == 'pull_request'
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: JSON Schema


      - name: create pull request comment
        if: steps.check-for-git-changes.outputs.changes == 'true' && github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            JSON Schema files have changed. Please run the following command to update the schemas:

            ```bash
            pnpm run generate:json-schemas
            ```

            This will update the JSON Schema files in the `packages/json-schemas/schemas` directory.
            Please commit the changes and push them to the pull request.

      - name: exit 1
        if: steps.check-for-git-changes.outputs.changes == 'true'
        run: |
          echo "exiting since we have changes"
          exit 1
